version: '3'

services:
  underwriter:
    user: root
    image: public.ecr.aws/c0j0y9o1/aline-banking-dh:aline-underwriter
    restart: 'always'
    ports: 
      - '8091:8091'
    env_file:
      - variables.env
  bank:
    user: root
    image: public.ecr.aws/c0j0y9o1/aline-banking-dh:aline-bank
    restart: 'always'
    ports: 
      - '8183:8183'
    env_file:
      - variables.env
  transaction:
    user: root
    image: public.ecr.aws/c0j0y9o1/aline-banking-dh:aline-transaction
    restart: 'always'
    ports: 
      - '8092:8092'
    env_file:
      - variables.env
  user:
    user: root
    image: public.ecr.aws/c0j0y9o1/aline-banking-dh:aline-user
    restart: 'always'
    ports: 
      - '8090:8090'
    env_file:
      - variables.env

